### ISSUE TITLE
Peer to Peer Code Review 28/02

### ISSUE THREAD

**Issue by ferbaco86** [ghamtre/AppleSolo#2]
- Suggestion: a gradient on the buttons can be added when you hover over them
- Avoid using the tag div inside a button

**Comment by idgm5** [comment]
@ferbaco86 Yes, I switch div containers for a span tag. Now span works as a block. 

I'll add a hover once the project is reviewed :)

Thanks for the observations!! :+1:

**Comment by idgm5** [comment]
I added hover colors to the site. 

Thank you, everyone, for your advice this morning!
